version: '3'
services: 
  db: 
    image: mysql:5.7 
    volumes: 
      - './.dbdata/db:/var/lib/mysql'
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  wordpress:
    depends_on: 
      - db 
    image: wordpress:latest
    links: 
      - db 
    ports:
      - '${APP_PORT}:80'
    restart: always
    volumes:
      - ./app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_DATABASE}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${DB_PREFIX}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - '${PMA_PORT}:80'
    restart: always
